# Generated by Django 4.2.3 on 2023-11-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
