# Generated by Django 4.2.3 on 2023-07-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="%Y/%m/%d"),
        ),
    ]
