# Generated by Django 4.2.3 on 2023-10-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
